version: '3.8'
services:
  # nest_db:
  #   image: postgres:15
  #   ports:
  #     - 5434:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: firstNest
  #   volumes:
  #     - dbdata6:/data/db
  #   networks:
  #     - first_nest
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shy
      - MONGO_INITDB_ROOT_PASSWORD=Shy@720
      - MONGO_INITDB_DATABASE=Nesti
    networks:
      - first_nest
# ----
  redis:
    image: 'redis:bookworm'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - dbdata6:/data/db
    networks:
      - first_nest

volumes:
  dbdata6:

networks:
  first_nest:
